package ro.uaic.dbxdrgsl.prefschedule.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import ro.uaic.dbxdrgsl.prefschedule.model.Student;

import java.util.List;
import java.util.Optional;

@Repository
public interface StudentRepository extends JpaRepository<Student, Long> {
    // Derived query - automatically generated by Spring Data JPA
    Optional<Student> findByCode(String code);
    
    // Derived query - find students by year
    List<Student> findByYear(int year);
    
    // JPQL query - find students by email domain
    @Query("SELECT s FROM Student s WHERE s.email LIKE CONCAT('%', :domain)")
    List<Student> findByEmailDomain(@Param("domain") String domain);
}
