spring.datasource.url=jdbc:h2:mem:worlddb;MODE=PostgreSQL;DATABASE_TO_UPPER=false
spring.datasource.username=sa
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
