spring:
  application:
    name: demo
  datasource:
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: DevHikariPool

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data-dev.sql

database:
  environment: development
  connection:
    host: localhost
    port: 9092
    name: devdb
    user: sa
    password: ""
    
logging:
  level:
    org.springframework.jdbc: DEBUG
    
server:
  port: 8081