server:
  port: 8079

spring:
  application:
    name: serviceB
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:8888"

management.endpoints.web.exposure.include: refresh,health,info
